version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: mern_backend
    ports:
      - "3200:3000"  # ✅ match internal backend port
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://konanoma777:TBNRFRAGS777@cluster0.osqqd4w.mongodb.net/Devops?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=Asjadkhazar
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    container_name: mern_frontend
    ports:
      - "5200:5000"  # ✅ match internal frontend port (from serve)
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
